CREATE TABLE `Catalogs` (
	`Id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`Node`	integer,
	`ParentID`	INTEGER,
	CONSTRAINT `CatalogsNode_Fk` FOREIGN KEY(`Node`) REFERENCES `RefNodes`(`Id`) ON DELETE CASCADE,
	CONSTRAINT `CatalogsParentId_Fk` FOREIGN KEY(`ParentID`) REFERENCES `Catalogs`(`Id`) ON DELETE CASCADE
);