DROP TABLE IF EXISTS LoadedContents;
CREATE TABLE `LoadedContents` (
	`Id`	    INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`ParentID`	INTEGER NOT NULL UNIQUE,
	`Content`	BLOB NOT NULL,
	CONSTRAINT 'LoadedContentUrlContent_Fk' FOREIGN KEY (ParentID) REFERENCES UrlContents (Id) ON DELETE CASCADE
);