CREATE TABLE RefNodes(
  Id   INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
  Name TEXT NOT NULL UNIQUE 
);

CREATE TABLE RefPathways(
  Id   INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
  Name TEXT NOT NULL UNIQUE 
);

CREATE TABLE RefImageTypes(
  Id   INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
  Name TEXT NOT NULL UNIQUE 
);

CREATE TABLE RefVideoTypes(
  Id   INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
  Name TEXT NOT NULL UNIQUE 
);

CREATE TABLE RefComments(
  Id   INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
  Name TEXT NOT NULL UNIQUE 
);