//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kaleidoscope.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Running")]
        public global::System.Threading.Tasks.TaskStatus MainTaskStatus {
            get {
                return ((global::System.Threading.Tasks.TaskStatus)(this["MainTaskStatus"]));
            }
            set {
                this["MainTaskStatus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CenterScreen")]
        public global::System.Windows.WindowStartupLocation MainWindowStartupLocation {
            get {
                return ((global::System.Windows.WindowStartupLocation)(this["MainWindowStartupLocation"]));
            }
            set {
                this["MainWindowStartupLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Maximized")]
        public global::System.Windows.WindowState MainWindowState {
            get {
                return ((global::System.Windows.WindowState)(this["MainWindowState"]));
            }
            set {
                this["MainWindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double MainWindowTop {
            get {
                return ((double)(this["MainWindowTop"]));
            }
            set {
                this["MainWindowTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double MainWindowLeft {
            get {
                return ((double)(this["MainWindowLeft"]));
            }
            set {
                this["MainWindowLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double MainWindowHeight {
            get {
                return ((double)(this["MainWindowHeight"]));
            }
            set {
                this["MainWindowHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double MainWindowWidth {
            get {
                return ((double)(this["MainWindowWidth"]));
            }
            set {
                this["MainWindowWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int SelectedValueRows {
            get {
                return ((int)(this["SelectedValueRows"]));
            }
            set {
                this["SelectedValueRows"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int SelectedValueColumns {
            get {
                return ((int)(this["SelectedValueColumns"]));
            }
            set {
                this["SelectedValueColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Все")]
        public string SelectedValueFillTypes {
            get {
                return ((string)(this["SelectedValueFillTypes"]));
            }
            set {
                this["SelectedValueFillTypes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int SelectedTimerInterval {
            get {
                return ((int)(this["SelectedTimerInterval"]));
            }
            set {
                this["SelectedTimerInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/Kaleidoscope;component/Resourses/Kaleidoscope.ico")]
        public string AppImage {
            get {
                return ((string)(this["AppImage"]));
            }
            set {
                this["AppImage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsDark {
            get {
                return ((bool)(this["IsDark"]));
            }
            set {
                this["IsDark"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Yellow")]
        public string AppPalettePrimaryName {
            get {
                return ((string)(this["AppPalettePrimaryName"]));
            }
            set {
                this["AppPalettePrimaryName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("lightblue")]
        public string AppPaletteAccentName {
            get {
                return ((string)(this["AppPaletteAccentName"]));
            }
            set {
                this["AppPaletteAccentName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("en-US")]
        public string Localization {
            get {
                return ((string)(this["Localization"]));
            }
            set {
                this["Localization"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SelectedIndexFillTypes {
            get {
                return ((int)(this["SelectedIndexFillTypes"]));
            }
            set {
                this["SelectedIndexFillTypes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Collapsed")]
        public global::System.Windows.Visibility ButtonTestVisibility {
            get {
                return ((global::System.Windows.Visibility)(this["ButtonTestVisibility"]));
            }
            set {
                this["ButtonTestVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public int ContentFoldersImageSelectedWidthItem {
            get {
                return ((int)(this["ContentFoldersImageSelectedWidthItem"]));
            }
            set {
                this["ContentFoldersImageSelectedWidthItem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public int ContentMainImageSelectedWidthItem {
            get {
                return ((int)(this["ContentMainImageSelectedWidthItem"]));
            }
            set {
                this["ContentMainImageSelectedWidthItem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public int ContentCatalogsImageSelectedWidthItem {
            get {
                return ((int)(this["ContentCatalogsImageSelectedWidthItem"]));
            }
            set {
                this["ContentCatalogsImageSelectedWidthItem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public int ContentFoldersImageSelectedHeightItem {
            get {
                return ((int)(this["ContentFoldersImageSelectedHeightItem"]));
            }
            set {
                this["ContentFoldersImageSelectedHeightItem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public int ContentMainImageSelectedHeightItem {
            get {
                return ((int)(this["ContentMainImageSelectedHeightItem"]));
            }
            set {
                this["ContentMainImageSelectedHeightItem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public int ContentCatalogsImageSelectedHeightItem {
            get {
                return ((int)(this["ContentCatalogsImageSelectedHeightItem"]));
            }
            set {
                this["ContentCatalogsImageSelectedHeightItem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsChangeSizeItemSeparatelyMainImage {
            get {
                return ((bool)(this["IsChangeSizeItemSeparatelyMainImage"]));
            }
            set {
                this["IsChangeSizeItemSeparatelyMainImage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsChangeSizeItemSeparatelyMainVideo {
            get {
                return ((bool)(this["IsChangeSizeItemSeparatelyMainVideo"]));
            }
            set {
                this["IsChangeSizeItemSeparatelyMainVideo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsChangeSizeItemSeparatelyFoldersImage {
            get {
                return ((bool)(this["IsChangeSizeItemSeparatelyFoldersImage"]));
            }
            set {
                this["IsChangeSizeItemSeparatelyFoldersImage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsChangeSizeItemSeparatelyFoldersVideo {
            get {
                return ((bool)(this["IsChangeSizeItemSeparatelyFoldersVideo"]));
            }
            set {
                this["IsChangeSizeItemSeparatelyFoldersVideo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsChangeSizeItemSeparatelyCatalogImage {
            get {
                return ((bool)(this["IsChangeSizeItemSeparatelyCatalogImage"]));
            }
            set {
                this["IsChangeSizeItemSeparatelyCatalogImage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsChangeSizeItemSeparatelyCatalogVideo {
            get {
                return ((bool)(this["IsChangeSizeItemSeparatelyCatalogVideo"]));
            }
            set {
                this["IsChangeSizeItemSeparatelyCatalogVideo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double RatioMainImageChangeSizeProportionally {
            get {
                return ((double)(this["RatioMainImageChangeSizeProportionally"]));
            }
            set {
                this["RatioMainImageChangeSizeProportionally"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double RatioMainVideoChangeSizeProportionally {
            get {
                return ((double)(this["RatioMainVideoChangeSizeProportionally"]));
            }
            set {
                this["RatioMainVideoChangeSizeProportionally"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double RatioFoldersImageChangeSizeProportionally {
            get {
                return ((double)(this["RatioFoldersImageChangeSizeProportionally"]));
            }
            set {
                this["RatioFoldersImageChangeSizeProportionally"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double RatioFoldersVideoChangeSizeProportionally {
            get {
                return ((double)(this["RatioFoldersVideoChangeSizeProportionally"]));
            }
            set {
                this["RatioFoldersVideoChangeSizeProportionally"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double RatioCatalogImageChangeSizeProportionally {
            get {
                return ((double)(this["RatioCatalogImageChangeSizeProportionally"]));
            }
            set {
                this["RatioCatalogImageChangeSizeProportionally"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double RatioCatalogVideoChangeSizeProportionally {
            get {
                return ((double)(this["RatioCatalogVideoChangeSizeProportionally"]));
            }
            set {
                this["RatioCatalogVideoChangeSizeProportionally"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsEnableRefreshContentFolders {
            get {
                return ((bool)(this["IsEnableRefreshContentFolders"]));
            }
            set {
                this["IsEnableRefreshContentFolders"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsEnableRefreshContentCatalogs {
            get {
                return ((bool)(this["IsEnableRefreshContentCatalogs"]));
            }
            set {
                this["IsEnableRefreshContentCatalogs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int NormalizedSizeImageMainIndex {
            get {
                return ((int)(this["NormalizedSizeImageMainIndex"]));
            }
            set {
                this["NormalizedSizeImageMainIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int NormalizedSizeImageFoldersIndex {
            get {
                return ((int)(this["NormalizedSizeImageFoldersIndex"]));
            }
            set {
                this["NormalizedSizeImageFoldersIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int NormalizedSizeImageCatalogsIndex {
            get {
                return ((int)(this["NormalizedSizeImageCatalogsIndex"]));
            }
            set {
                this["NormalizedSizeImageCatalogsIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int SizePageImageLoadMainIndex {
            get {
                return ((int)(this["SizePageImageLoadMainIndex"]));
            }
            set {
                this["SizePageImageLoadMainIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int SizePageImageLoadFoldersIndex {
            get {
                return ((int)(this["SizePageImageLoadFoldersIndex"]));
            }
            set {
                this["SizePageImageLoadFoldersIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int SizePageImageLoadCatalogsIndex {
            get {
                return ((int)(this["SizePageImageLoadCatalogsIndex"]));
            }
            set {
                this["SizePageImageLoadCatalogsIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsKindContentMain {
            get {
                return ((bool)(this["IsKindContentMain"]));
            }
            set {
                this["IsKindContentMain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsKindContentFolders {
            get {
                return ((bool)(this["IsKindContentFolders"]));
            }
            set {
                this["IsKindContentFolders"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsKindContentCatalogs {
            get {
                return ((bool)(this["IsKindContentCatalogs"]));
            }
            set {
                this["IsKindContentCatalogs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int ContentMainVideoSelectedWidthItem {
            get {
                return ((int)(this["ContentMainVideoSelectedWidthItem"]));
            }
            set {
                this["ContentMainVideoSelectedWidthItem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int ContentFoldersVideoSelectedWidthItem {
            get {
                return ((int)(this["ContentFoldersVideoSelectedWidthItem"]));
            }
            set {
                this["ContentFoldersVideoSelectedWidthItem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int ContentCatalogsVideoSelectedWidthItem {
            get {
                return ((int)(this["ContentCatalogsVideoSelectedWidthItem"]));
            }
            set {
                this["ContentCatalogsVideoSelectedWidthItem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int ContentMainVideoSelectedHeightItem {
            get {
                return ((int)(this["ContentMainVideoSelectedHeightItem"]));
            }
            set {
                this["ContentMainVideoSelectedHeightItem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int ContentFoldersVideoSelectedHeightItem {
            get {
                return ((int)(this["ContentFoldersVideoSelectedHeightItem"]));
            }
            set {
                this["ContentFoldersVideoSelectedHeightItem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int ContentCatalogsVideoSelectedHeightItem {
            get {
                return ((int)(this["ContentCatalogsVideoSelectedHeightItem"]));
            }
            set {
                this["ContentCatalogsVideoSelectedHeightItem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int SizePageVideoLoadMainIndex {
            get {
                return ((int)(this["SizePageVideoLoadMainIndex"]));
            }
            set {
                this["SizePageVideoLoadMainIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int SizePageVideoLoadFoldersIndex {
            get {
                return ((int)(this["SizePageVideoLoadFoldersIndex"]));
            }
            set {
                this["SizePageVideoLoadFoldersIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int SizePageVideoLoadCatalogsIndex {
            get {
                return ((int)(this["SizePageVideoLoadCatalogsIndex"]));
            }
            set {
                this["SizePageVideoLoadCatalogsIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsModeShowMainImage {
            get {
                return ((bool)(this["IsModeShowMainImage"]));
            }
            set {
                this["IsModeShowMainImage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsModeShowFoldersImage {
            get {
                return ((bool)(this["IsModeShowFoldersImage"]));
            }
            set {
                this["IsModeShowFoldersImage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsModeShowCatalogsImage {
            get {
                return ((bool)(this["IsModeShowCatalogsImage"]));
            }
            set {
                this["IsModeShowCatalogsImage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsModeShowMainVideo {
            get {
                return ((bool)(this["IsModeShowMainVideo"]));
            }
            set {
                this["IsModeShowMainVideo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsModeShowFoldersVideo {
            get {
                return ((bool)(this["IsModeShowFoldersVideo"]));
            }
            set {
                this["IsModeShowFoldersVideo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsModeShowCatalogsVideo {
            get {
                return ((bool)(this["IsModeShowCatalogsVideo"]));
            }
            set {
                this["IsModeShowCatalogsVideo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800")]
        public int ContentMainImageOneToListSelectedWidth {
            get {
                return ((int)(this["ContentMainImageOneToListSelectedWidth"]));
            }
            set {
                this["ContentMainImageOneToListSelectedWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800")]
        public int ContentFoldersImageOneToListSelectedWidth {
            get {
                return ((int)(this["ContentFoldersImageOneToListSelectedWidth"]));
            }
            set {
                this["ContentFoldersImageOneToListSelectedWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800")]
        public int ContentCatalogImageOneToListSelectedWidth {
            get {
                return ((int)(this["ContentCatalogImageOneToListSelectedWidth"]));
            }
            set {
                this["ContentCatalogImageOneToListSelectedWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800")]
        public int ContentMainImageOneToListSelectedHeight {
            get {
                return ((int)(this["ContentMainImageOneToListSelectedHeight"]));
            }
            set {
                this["ContentMainImageOneToListSelectedHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800")]
        public int ContentFoldersImageOneToListSelectedHeight {
            get {
                return ((int)(this["ContentFoldersImageOneToListSelectedHeight"]));
            }
            set {
                this["ContentFoldersImageOneToListSelectedHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800")]
        public int ContentCatalogImageOneToListSelectedHeight {
            get {
                return ((int)(this["ContentCatalogImageOneToListSelectedHeight"]));
            }
            set {
                this["ContentCatalogImageOneToListSelectedHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsChangeSizeItemSeparatelyMainOneToListImage {
            get {
                return ((bool)(this["IsChangeSizeItemSeparatelyMainOneToListImage"]));
            }
            set {
                this["IsChangeSizeItemSeparatelyMainOneToListImage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsChangeSizeItemSeparatelyFoldersOneToListImage {
            get {
                return ((bool)(this["IsChangeSizeItemSeparatelyFoldersOneToListImage"]));
            }
            set {
                this["IsChangeSizeItemSeparatelyFoldersOneToListImage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsChangeSizeItemSeparatelyCatalogOneToListImage {
            get {
                return ((bool)(this["IsChangeSizeItemSeparatelyCatalogOneToListImage"]));
            }
            set {
                this["IsChangeSizeItemSeparatelyCatalogOneToListImage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsChangeSizeItemSeparatelyMainOneToListVideo {
            get {
                return ((bool)(this["IsChangeSizeItemSeparatelyMainOneToListVideo"]));
            }
            set {
                this["IsChangeSizeItemSeparatelyMainOneToListVideo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsChangeSizeItemSeparatelyFoldersOneToListVideo {
            get {
                return ((bool)(this["IsChangeSizeItemSeparatelyFoldersOneToListVideo"]));
            }
            set {
                this["IsChangeSizeItemSeparatelyFoldersOneToListVideo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsChangeSizeItemSeparatelyCatalogOneToListVideo {
            get {
                return ((bool)(this["IsChangeSizeItemSeparatelyCatalogOneToListVideo"]));
            }
            set {
                this["IsChangeSizeItemSeparatelyCatalogOneToListVideo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double RatioMainImageOneToListChangeSizeProportionally {
            get {
                return ((double)(this["RatioMainImageOneToListChangeSizeProportionally"]));
            }
            set {
                this["RatioMainImageOneToListChangeSizeProportionally"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double RatioFoldersImageOneToListChangeSizeProportionally {
            get {
                return ((double)(this["RatioFoldersImageOneToListChangeSizeProportionally"]));
            }
            set {
                this["RatioFoldersImageOneToListChangeSizeProportionally"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double RatioCatalogsImageOneToListChangeSizeProportionally {
            get {
                return ((double)(this["RatioCatalogsImageOneToListChangeSizeProportionally"]));
            }
            set {
                this["RatioCatalogsImageOneToListChangeSizeProportionally"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double RatioMainVideoOneToListChangeSizeProportionally {
            get {
                return ((double)(this["RatioMainVideoOneToListChangeSizeProportionally"]));
            }
            set {
                this["RatioMainVideoOneToListChangeSizeProportionally"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double RatioFoldersVideoOneToListChangeSizeProportionally {
            get {
                return ((double)(this["RatioFoldersVideoOneToListChangeSizeProportionally"]));
            }
            set {
                this["RatioFoldersVideoOneToListChangeSizeProportionally"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double RatioCatalogsVideoOneToListChangeSizeProportionally {
            get {
                return ((double)(this["RatioCatalogsVideoOneToListChangeSizeProportionally"]));
            }
            set {
                this["RatioCatalogsVideoOneToListChangeSizeProportionally"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int ContentMainVideoOneToListSelectedWidth {
            get {
                return ((int)(this["ContentMainVideoOneToListSelectedWidth"]));
            }
            set {
                this["ContentMainVideoOneToListSelectedWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int ContentMainVideoOneToListSelectedHeight {
            get {
                return ((int)(this["ContentMainVideoOneToListSelectedHeight"]));
            }
            set {
                this["ContentMainVideoOneToListSelectedHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800")]
        public int ContentFoldersVideoOneToListSelectedWidth {
            get {
                return ((int)(this["ContentFoldersVideoOneToListSelectedWidth"]));
            }
            set {
                this["ContentFoldersVideoOneToListSelectedWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800")]
        public int ContentFoldersVideoOneToListSelectedHeight {
            get {
                return ((int)(this["ContentFoldersVideoOneToListSelectedHeight"]));
            }
            set {
                this["ContentFoldersVideoOneToListSelectedHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800")]
        public int ContentCatalogsVideoOneToListSelectedWidth {
            get {
                return ((int)(this["ContentCatalogsVideoOneToListSelectedWidth"]));
            }
            set {
                this["ContentCatalogsVideoOneToListSelectedWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800")]
        public int ContentCatalogsVideoOneToListSelectedHeight {
            get {
                return ((int)(this["ContentCatalogsVideoOneToListSelectedHeight"]));
            }
            set {
                this["ContentCatalogsVideoOneToListSelectedHeight"] = value;
            }
        }
    }
}
