//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kaleidoscope.Localization {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AboutTheProgramRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AboutTheProgramRes() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kaleidoscope.Localization.AboutTheProgramRes", typeof(AboutTheProgramRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на EXPLORE.
        /// </summary>
        internal static string ButtonExploreCaption {
            get {
                return ResourceManager.GetString("ButtonExploreCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Click to configure advanced settings.
        /// </summary>
        internal static string ButtonExploreToolTipAddCaption {
            get {
                return ResourceManager.GetString("ButtonExploreToolTipAddCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Click to enter the main menu.
        /// </summary>
        internal static string ButtonExploreToolTipMainCaption {
            get {
                return ResourceManager.GetString("ButtonExploreToolTipMainCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Two types of fill: gradient and radial.
        /// </summary>
        internal static string CardColors01 {
            get {
                return ResourceManager.GetString("CardColors01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Random generation of fill type, color set and fill direction.
        /// </summary>
        internal static string CardColors02 {
            get {
                return ResourceManager.GetString("CardColors02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dynamic setting of parameters :
        ///number of columns (1-100)
        ///number of lines (1-100)
        ///type of filling (random, gradient, radial)
        ///interval of generation (1 ms - 5 sec).
        /// </summary>
        internal static string CardColors03 {
            get {
                return ResourceManager.GetString("CardColors03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Multi-gradient kaleidoscope.
        /// </summary>
        internal static string CardColorsCation {
            get {
                return ResourceManager.GetString("CardColorsCation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Development Tools.
        /// </summary>
        internal static string CardDevelopmentToolsCaption {
            get {
                return ResourceManager.GetString("CardDevelopmentToolsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Material Design In XAML Toolkit.
        /// </summary>
        internal static string CardDevelopmentToolsMaterialDesignText {
            get {
                return ResourceManager.GetString("CardDevelopmentToolsMaterialDesignText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Using the Model-View-ViewModel Design Pattern.
        /// </summary>
        internal static string CardDevelopmentToolsMVVMText {
            get {
                return ResourceManager.GetString("CardDevelopmentToolsMVVMText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SQLite - сompact embedded relational database.
        /// </summary>
        internal static string CardDevelopmentToolsSQLiteText {
            get {
                return ResourceManager.GetString("CardDevelopmentToolsSQLiteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Manager of images and videos.
        /// </summary>
        internal static string CardImagesCaption {
            get {
                return ResourceManager.GetString("CardImagesCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Main Features.
        /// </summary>
        internal static string CardMainFeatures {
            get {
                return ResourceManager.GetString("CardMainFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Language localization.
        /// </summary>
        internal static string CardMainFeatures01 {
            get {
                return ResourceManager.GetString("CardMainFeatures01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Color theme: light or dark.
        /// </summary>
        internal static string CardMainFeatures02 {
            get {
                return ResourceManager.GetString("CardMainFeatures02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Customize the color palette of the user interface.
        /// </summary>
        internal static string CardMainFeatures03 {
            get {
                return ResourceManager.GetString("CardMainFeatures03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Saving custom settings:
        ///screen coordinates of the application window,
        ///functional parameters of the relevant pages.
        /// </summary>
        internal static string CardMainFeatures04 {
            get {
                return ResourceManager.GetString("CardMainFeatures04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tic-Tac-Toe.
        /// </summary>
        internal static string CardTicTacToeCaption {
            get {
                return ResourceManager.GetString("CardTicTacToeCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About program.
        /// </summary>
        internal static string HeaderCaption {
            get {
                return ResourceManager.GetString("HeaderCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Welcome to my first WPF solutions.
        /// </summary>
        internal static string WelcomeCaption {
            get {
                return ResourceManager.GetString("WelcomeCaption", resourceCulture);
            }
        }
    }
}
