//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kaleidoscope.Localization {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ContentFoldersRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContentFoldersRes() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kaleidoscope.Localization.ContentFoldersRes", typeof(ContentFoldersRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Number of 
        ///image files.
        /// </summary>
        internal static string CaptionCountImageType {
            get {
                return ResourceManager.GetString("CaptionCountImageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Number of 
        ///video files.
        /// </summary>
        internal static string CaptionCountVideoType {
            get {
                return ResourceManager.GetString("CaptionCountVideoType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Folders.
        /// </summary>
        internal static string CaptionName {
            get {
                return ResourceManager.GetString("CaptionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sync of folder.
        /// </summary>
        internal static string FolderSync {
            get {
                return ResourceManager.GetString("FolderSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Are you sure you want to stop syncing folders.
        /// </summary>
        internal static string InterruptSyncFoldersConfirm {
            get {
                return ResourceManager.GetString("InterruptSyncFoldersConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Manager of images and videos: Folders.
        /// </summary>
        internal static string MainHeaderTitle {
            get {
                return ResourceManager.GetString("MainHeaderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select a folder with images and videos.
        /// </summary>
        internal static string MsgDescriptionFolderBrowserDialog {
            get {
                return ResourceManager.GetString("MsgDescriptionFolderBrowserDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Catalog not found.
        /// </summary>
        internal static string MsgDirectoryNotFound {
            get {
                return ResourceManager.GetString("MsgDirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Synchronization results report.
        /// </summary>
        internal static string ReportSyncFolders {
            get {
                return ResourceManager.GetString("ReportSyncFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Registered files.
        /// </summary>
        internal static string ReportSyncFoldersAddFiles {
            get {
                return ResourceManager.GetString("ReportSyncFoldersAddFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Added folders.
        /// </summary>
        internal static string ReportSyncFoldersAddFolders {
            get {
                return ResourceManager.GetString("ReportSyncFoldersAddFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Checked files.
        /// </summary>
        internal static string ReportSyncFoldersCheckFiles {
            get {
                return ResourceManager.GetString("ReportSyncFoldersCheckFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Deleted of registration records about files.
        /// </summary>
        internal static string ReportSyncFoldersDelRegisteresFiles {
            get {
                return ResourceManager.GetString("ReportSyncFoldersDelRegisteresFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Empty folders.
        /// </summary>
        internal static string ReportSyncFoldersEmptyFolders {
            get {
                return ResourceManager.GetString("ReportSyncFoldersEmptyFolders", resourceCulture);
            }
        }
    }
}
