//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kaleidoscope.Localization {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ImagesRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ImagesRes() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kaleidoscope.Localization.ImagesRes", typeof(ImagesRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Catalog.
        /// </summary>
        internal static string ContentMenuItemCatalog {
            get {
                return ResourceManager.GetString("ContentMenuItemCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Items of the catalog.
        /// </summary>
        internal static string ContentMenuItemCatalogItems {
            get {
                return ResourceManager.GetString("ContentMenuItemCatalogItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Comments.
        /// </summary>
        internal static string ContentMenuItemComments {
            get {
                return ResourceManager.GetString("ContentMenuItemComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Content.
        /// </summary>
        internal static string ContentMenuItemContent {
            get {
                return ResourceManager.GetString("ContentMenuItemContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Folders.
        /// </summary>
        internal static string ContentMenuItemFolders {
            get {
                return ResourceManager.GetString("ContentMenuItemFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Types of image files.
        /// </summary>
        internal static string ContentMenuItemImageTypes {
            get {
                return ResourceManager.GetString("ContentMenuItemImageTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Types of video files.
        /// </summary>
        internal static string ContentMenuItemVideoTypes {
            get {
                return ResourceManager.GetString("ContentMenuItemVideoTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Manager of images and videos.
        /// </summary>
        internal static string HeaderCaption {
            get {
                return ResourceManager.GetString("HeaderCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enable/Disable loading 
        ///multimedia content.
        /// </summary>
        internal static string HeaderControlButtonIsEnableRefreshContentVisibility {
            get {
                return ResourceManager.GetString("HeaderControlButtonIsEnableRefreshContentVisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Size customize mode: 
        ///proportional or separate.
        /// </summary>
        internal static string HeaderControlButtonModeChangeSizeItem {
            get {
                return ResourceManager.GetString("HeaderControlButtonModeChangeSizeItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Display mode: 
        ///list or one of the list.
        /// </summary>
        internal static string HeaderControlButtonModeShowContent {
            get {
                return ResourceManager.GetString("HeaderControlButtonModeShowContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show images or video.
        /// </summary>
        internal static string HeaderControlButtonShowTypeContent {
            get {
                return ResourceManager.GetString("HeaderControlButtonShowTypeContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Height.
        /// </summary>
        internal static string HeaderControlCaptionHeightItem {
            get {
                return ResourceManager.GetString("HeaderControlCaptionHeightItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Width.
        /// </summary>
        internal static string HeaderControlCaptionWidthItem {
            get {
                return ResourceManager.GetString("HeaderControlCaptionWidthItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Page first.
        /// </summary>
        internal static string HeaderControlPagesManagerButtonFirst {
            get {
                return ResourceManager.GetString("HeaderControlPagesManagerButtonFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Page last.
        /// </summary>
        internal static string HeaderControlPagesManagerButtonLast {
            get {
                return ResourceManager.GetString("HeaderControlPagesManagerButtonLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Page next.
        /// </summary>
        internal static string HeaderControlPagesManagerButtonNext {
            get {
                return ResourceManager.GetString("HeaderControlPagesManagerButtonNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Page previous.
        /// </summary>
        internal static string HeaderControlPagesManagerButtonPrevious {
            get {
                return ResourceManager.GetString("HeaderControlPagesManagerButtonPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pages Manager.
        /// </summary>
        internal static string HeaderControlPopupBoxPagesManager {
            get {
                return ResourceManager.GetString("HeaderControlPopupBoxPagesManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Repeat loading 
        ///multimedia content.
        /// </summary>
        internal static string HeaderControlRepeatLoadingContent {
            get {
                return ResourceManager.GetString("HeaderControlRepeatLoadingContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Number of uploaded images (page size).
        /// </summary>
        internal static string OptionsImagePageSize {
            get {
                return ResourceManager.GetString("OptionsImagePageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Management options of media content.
        /// </summary>
        internal static string OptionsManagerContentCaption {
            get {
                return ResourceManager.GetString("OptionsManagerContentCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Normalize image format at load.
        /// </summary>
        internal static string OptionsMediaNormalizedSizeImage {
            get {
                return ResourceManager.GetString("OptionsMediaNormalizedSizeImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Number of uploaded videos (page size).
        /// </summary>
        internal static string OptionsVideoPageSize {
            get {
                return ResourceManager.GetString("OptionsVideoPageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Full screen mode.
        /// </summary>
        internal static string PopupBoxButtonFullscreen {
            get {
                return ResourceManager.GetString("PopupBoxButtonFullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mark / cancel mark.
        /// </summary>
        internal static string PopupBoxButtonMarked {
            get {
                return ResourceManager.GetString("PopupBoxButtonMarked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mark All.
        /// </summary>
        internal static string PopupBoxButtonMarkedAll {
            get {
                return ResourceManager.GetString("PopupBoxButtonMarkedAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel all marks.
        /// </summary>
        internal static string PopupBoxButtonMarkedCancelAll {
            get {
                return ResourceManager.GetString("PopupBoxButtonMarkedCancelAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invert.
        /// </summary>
        internal static string PopupBoxButtonMarkedInverse {
            get {
                return ResourceManager.GetString("PopupBoxButtonMarkedInverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Property.
        /// </summary>
        internal static string PopupBoxButtonProperty {
            get {
                return ResourceManager.GetString("PopupBoxButtonProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rotate Left 90º.
        /// </summary>
        internal static string PopupBoxButtonRotateLeft {
            get {
                return ResourceManager.GetString("PopupBoxButtonRotateLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rotate right by 90º.
        /// </summary>
        internal static string PopupBoxButtonRotateRight {
            get {
                return ResourceManager.GetString("PopupBoxButtonRotateRight", resourceCulture);
            }
        }
    }
}
